"""Dataclasses + serialization helpers for optimization session I/O.

Schemas covered here:
- ``Proposal``        -> ``iter_<k>/trial_<m>/proposal.json``
- ``TrialResult``     -> ``iter_<k>/trial_<m>/trial_result.json``
- ``Evaluation``      -> one row inside ``iter_<k>/evaluations.json``
- ``IterEvaluations`` -> ``iter_<k>/evaluations.json``
- ``LeaderboardRow``  -> rows in ``iter_<k>/leaderboard.csv`` &
                        ``<session>/leaderboard.csv``
- ``SessionSummary``  -> ``<session>/session_summary.json``

All payloads are stdlib-only so the loop never imports pydantic /
pandas / numpy as a dependency. JSON is written with ``indent=2`` to
keep diffs review-friendly.
"""

from __future__ import annotations

import csv
import dataclasses as _dc
import json
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence


# -----------------------------------------------------------------------
# Trial-level schemas
# -----------------------------------------------------------------------

VALID_ORIGINS = (
    "default",        # trial_0 of iter_0 -> strategy default params
    "grid",           # neighbourhood enumeration
    "random",         # uniform random in search space
    "bayesian",       # optuna-backed sampler (optional)
    "local-perturb",  # small step around a parent trial
    "explore",        # one-off exploratory probe
    "llm",            # produced by the optional LLM channel
)

VALID_TRIAL_STATUS = (
    "ok",
    "failed",
    "injection_mismatch",
    "skipped",
    "patch_invalid",
    "missing_summary",
    "dry",
)


@dataclass
class Proposal:
    """A single trial proposal generated by the Optimizer subagent."""

    trial_id: str
    iter_idx: int
    trial_idx: int
    origin: str
    parent_trial: str | None
    changed_params: dict[str, Any]
    full_params: dict[str, Any]
    rationale: str
    predicted_metric_direction: str = "unknown"  # up / down / unknown

    def __post_init__(self) -> None:
        if self.origin not in VALID_ORIGINS:
            raise ValueError(
                f"unknown proposal origin: {self.origin!r}; "
                f"allowed = {VALID_ORIGINS!r}"
            )
        if self.predicted_metric_direction not in ("up", "down", "unknown"):
            raise ValueError(
                "predicted_metric_direction must be one of "
                "{'up','down','unknown'}, got "
                f"{self.predicted_metric_direction!r}"
            )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class TrialResult:
    """Outcome of a single trial after running the backtest engine."""

    trial_id: str
    iter_idx: int
    trial_idx: int
    trial_status: str
    summary: dict[str, Any] | None
    error: str | None = None
    duration_sec: float | None = None
    artefact_dir: str | None = None  # path string for portability

    def __post_init__(self) -> None:
        if self.trial_status not in VALID_TRIAL_STATUS:
            raise ValueError(
                f"invalid trial_status {self.trial_status!r}; "
                f"allowed = {VALID_TRIAL_STATUS!r}"
            )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# -----------------------------------------------------------------------
# Evaluation-level schemas
# -----------------------------------------------------------------------


@dataclass
class Evaluation:
    """Per-trial evaluation row produced by the Evaluator subagent."""

    trial_id: str
    iter_idx: int
    trial_idx: int
    status: str  # mirrors trial_status; "ok" | "missing_summary" | ...
    score: float | None
    metrics: dict[str, Any]
    diagnostics: dict[str, Any] = field(default_factory=dict)
    rank: int | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class IterEvaluations:
    """The complete evaluator output for a single iteration."""

    iter_idx: int
    score_formula: dict[str, Any]
    evaluations: list[Evaluation]
    top_k: list[str]
    best_score: float | None
    delta_vs_prev: float | None
    delta_vs_baseline: float | None
    decision: str  # "continue" | "stop"
    stop_reason: str | None
    llm_notes: dict[str, Any] | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "iter_idx": self.iter_idx,
            "score_formula": self.score_formula,
            "evaluations": [e.to_dict() for e in self.evaluations],
            "top_k": list(self.top_k),
            "best_score": self.best_score,
            "delta_vs_prev": self.delta_vs_prev,
            "delta_vs_baseline": self.delta_vs_baseline,
            "decision": self.decision,
            "stop_reason": self.stop_reason,
            "llm_notes": self.llm_notes,
        }


# -----------------------------------------------------------------------
# Leaderboard / session-summary schemas
# -----------------------------------------------------------------------

LEADERBOARD_FIELDS: tuple[str, ...] = (
    "iter_idx",
    "trial_idx",
    "trial_id",
    "origin",
    "status",
    "score",
    "total_return_pct",
    "annualised_return_pct",
    "max_drawdown_pct",
    "trade_count",
    "sharpe_proxy",
    "calmar_proxy",
)


@dataclass
class LeaderboardRow:
    iter_idx: int
    trial_idx: int
    trial_id: str
    origin: str
    status: str
    score: float | None
    total_return_pct: float | None
    annualised_return_pct: float | None
    max_drawdown_pct: float | None
    trade_count: int | None
    sharpe_proxy: float | None
    calmar_proxy: float | None

    def to_csv_row(self) -> dict[str, Any]:
        return {k: getattr(self, k) for k in LEADERBOARD_FIELDS}


@dataclass
class SessionSummary:
    session_id: str
    namespace: str
    started_at: str  # ISO-8601 UTC
    finished_at: str  # ISO-8601 UTC
    iterations: int
    total_trials: int
    best_trial_path: str | None
    best_score: float | None
    stop_reason: str
    cli_args: dict[str, Any] = field(default_factory=dict)
    pool_config_path: str | None = None
    search_space_path: str | None = None
    score_formula: dict[str, Any] | None = None
    runtime_sec: float | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# -----------------------------------------------------------------------
# IO helpers
# -----------------------------------------------------------------------


def write_json(path: Path, payload: Mapping[str, Any] | Sequence[Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2, sort_keys=False, default=str)
        fh.write("\n")
    tmp.replace(path)


def read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def write_leaderboard_csv(path: Path, rows: Iterable[LeaderboardRow]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(LEADERBOARD_FIELDS))
        writer.writeheader()
        for row in rows:
            writer.writerow(row.to_csv_row())
    tmp.replace(path)


def read_leaderboard_csv(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


__all__ = [
    "Evaluation",
    "IterEvaluations",
    "LEADERBOARD_FIELDS",
    "LeaderboardRow",
    "Proposal",
    "SessionSummary",
    "TrialResult",
    "VALID_ORIGINS",
    "VALID_TRIAL_STATUS",
    "read_json",
    "read_leaderboard_csv",
    "write_json",
    "write_leaderboard_csv",
]
